### ISSUE TITLE
Easing seems to be applied incorrectly

### ISSUE THREAD

**Issue by keerifox** [JRiggles/EaseSprite#1]
Easing functions take in the animation time (from 0 to 1) and return animation frame (from 0 to 1), but in the code below we pass the animation frame `a` and expect it to return the animation time (with the intention to distribute it across multiple frames).

https://github.com/JRiggles/EaseSprite/blob/b64a7676f1d3203ac8a75fbecd0c807aee3aefdc/extension/easeprite.lua#L161-L172

In the example with [easeInOutExpo](https://easings.net/#easeInOutExpo), which is expected to spend least time in the middle frames, the extension assigns middle frames the most time, since the jump from 0.20 frame to 0.50 frame is interpreted as "this frame must be assigned 0.30 of the total animation duration".

**Comment by JRiggles** [comment]
@keerifox Hey, thanks for the heads-up! I'll look into this when I have a chance - it's possible my math got mixed up as I was translating the functions from [easings.net](https://easings.net).

**Comment by JRiggles** [comment]
Fixed! v1.1.0 will be up on Itch shortly!
